version: "3.8"

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-db-data:/var/lib/mysql
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    image: userscores_back
    ports:
      - 8000:3000
    volumes:
      - ./backend:/backend
      - "/backend/node_modules"
    depends_on:
      - db
    restart: always
    stdin_open: true
    tty: true
  frontend:
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    image: userscores_front
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/frontend
      - "/frontend/node_modules"
    stdin_open: true
    tty: true

volumes:
  mysql-db-data:
